default_group = "work"
active_only = true

[groups.work]
accounts = ["user@example.com:google"]
calendars = ["Jeremy Brown", "Holidays in France"]

[groups.personal]
accounts = ["personal@example.com:fastmail"]
calendars = ["ğŸ‘±â€â™‚ï¸ Jeremy"]

[groups.family]
accounts = ["personal@example.com:fastmail"]
calendars = ["ğŸ‘¦ Child", "Personal & Family", "ğŸ‘±â€â™‚ï¸ Jeremy"]

# "all" is built-in â€” no filtering
